version: '2.1'
services:
  # Zeppelin 0.9 Preview1: 
  # to access docker-compose exec -t zeppelin
  zeppelin:
    build: zeppelin
    image: zeppelin09p
    depends_on:
      - jobmanager
    ports:
      - 8080:8080
    volumes:
      # we copied the conf out: `docker cp df7baadfdb2f:/zeppelin/conf .`
      - ./zeppelin/conf:/zeppelin/conf
    # command: "/bin/bash"
    # stdin_open: true
    # tty: true    
    # volumes:
    #   - ./conf:/opt/flink/conf
    #   - flink-checkpoints-directory:/tmp/flink-checkpoints-directory
    #   - /tmp/flink-savepoints-directory:/tmp/flink-savepoints-directory
    # environment:
    #   - JOB_MANAGER_RPC_ADDRESS=jobmanager
  # flink job manager and task manager
  jobmanager:
    # build: flinkcli
    image: flink:1.10.0-scala_2.11
    command: "jobmanager.sh start-foreground"
    ports:
      - 8081:8081
    volumes:
      - ./conf:/opt/flink/conf
      - flink-checkpoints-directory:/tmp/flink-checkpoints-directory
      - /tmp/flink-savepoints-directory:/tmp/flink-savepoints-directory
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
  taskmanager:
    image: flink:1.10.0-scala_2.11
    depends_on:
      - jobmanager
    command: "taskmanager.sh start-foreground"
    volumes:
      - ./conf:/opt/flink/conf
      - flink-checkpoints-directory:/tmp/flink-checkpoints-directory
      - /tmp/flink-savepoints-directory:/tmp/flink-savepoints-directory
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

volumes:
  flink-checkpoints-directory:
      